version: '3'
services:
  airflow:
    image: ${QUAY_ACCOUNT}/airflow:${IMAGE_TAG}
    build: 
      context: ./images/airflow
      args: 
        AIRFLOW_IMAGE_TAG: ${AIRFLOW_IMAGE_TAG}
  airflow-ansible:
    image: ${QUAY_ACCOUNT}/airflow-ansible:${IMAGE_TAG}
    build: 
      context: ./images/airflow-ansible
      args:
        BASE_IMAGE: ${QUAY_ACCOUNT}/airflow:${IMAGE_TAG}
    depends_on:
      - airflow
  airflow-managed-services:
    image: ${QUAY_ACCOUNT}/airflow-managed-services:${IMAGE_TAG}
    build: 
      context: ./images/airflow-managed-services
      args:
        BASE_IMAGE: ${QUAY_ACCOUNT}/airflow:${IMAGE_TAG}
    depends_on:
      - airflow 
  airflow-jetski:
    image: ${QUAY_ACCOUNT}/airflow-jetski:${IMAGE_TAG}
    build:
      context: ./images/airflow-jetski
