QUAY_ACCOUNT ?= quay.io/cloud-bulldozer
IMAGE_BUILDER ?= podman
AIRFLOW_VERSION ?= 2.1.3
AIRFLOW_PYTHON_VERSION ?= python3.8
AIRFLOW_IMAGE_TAG ?= $(AIRFLOW_VERSION)-$(AIRFLOW_PYTHON_VERSION)
IMAGE_TAG ?= $(AIRFLOW_VERSION)

BASE_IMAGE ?= $(QUAY_ACCOUNT)/airflow-base:$(IMAGE_TAG)


.PHONY: all
all: build push

build:
	QUAY_ACCOUNT=$(QUAY_ACCOUNT) IMAGE_TAG=$(IMAGE_TAG) AIRFLOW_IMAGE_TAG=$(AIRFLOW_IMAGE_TAG) $(IMAGE_BUILDER)-compose build 

push:
	QUAY_ACCOUNT=$(QUAY_ACCOUNT) IMAGE_TAG=$(IMAGE_TAG) AIRFLOW_IMAGE_TAG=$(AIRFLOW_IMAGE_TAG) $(IMAGE_BUILDER)-compose push 
