nameOverride: ""
fullnameOverride: ""

global:
  baseDomain: ""
  repo:
    url: https://github.com/whitleykeith/airflow-kubernetes.git
    branch: master


airflow:
  syncWave: 0
  hostName: airflow
  chartVersion: 1.1.0
  values: 
    executor: KubernetesExecutor
    defaultAirflowRepository: quay.io/cloud-bulldozer/airflow
    defaultAirflowTag: 2.1.3
    airflowVersion: 2.1.3
    config:
      logging:
        colored_console_log: "False"
        remote_logging: "True"
        remote_base_log_folder: s3://perfscale-airflow-logs/ci
        remote_log_conn_id: S3Logs
      kubernetes:
        delete_worker_pods: True
      core:
        DAGBAG_IMPORT_TIMEOUT: 300
        killed_task_cleanup_time: 604800
      scheduler:
        scheduler_heartbeat_sec: 10
        processor_poll_interval: 30
      secrets:
        backend: airflow.providers.hashicorp.secrets.vault.VaultBackend
        backend_kwargs: '{"connections_path": "connections", "variables_path": "variables", "kubernetes_role": "airflow", "auth_type": "kubernetes", "mount_point": "airflow", "url": "http://vault.vault.svc.cluster.local:8200"}'
    dags:
      gitSync:
        enabled: true
        subPath: dags
        depth: 8
    webserver:
      replicas: 3
    migrateDatabaseJob:
      jobAnnotations:
        "argocd.argoproj.io/hook": "Sync"
        "argocd.argoproj.io/hook-delete-policy": "BeforeHookCreation"
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-weight": ""
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded


argo:
  syncWave: 0
  hostName: argo
  values: {}


results:
  syncWave: 1
  dashboard:
    values:
      elasticsearch:
        url: perf-results-es-http.perf-results.svc.cluster.local:9200
        indice: perf_scale_ci
        username: elastic
  elastic:
    enabled: false 
    values:
      elasticsearch:
        nodeSets:
        - name: default      
          count: 3
          volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
          config:
            node.store.allow_mmap: false
            xpack.security.authc:
              anonymous:
                username: anonymous_user
                roles: superuser
          podTemplate:
            spec:
              containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 16Gi
                securityContext:
                  capabilities:
                    add: ["SYS_CHROOT"]


logging: 
  syncWave: 0
  fluentd:
    mergeJsonLogs: false
    values: {}
  elastic:
    values:
      elasticsearch:
        nodeSets:
        - name: default      
          count: 3
          volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
          config:
            node.store.allow_mmap: false
            xpack.security.authc:
              anonymous:
                username: anonymous_user
                roles: superuser
          podTemplate:
            spec:
              containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 16Gi
                securityContext:
                  capabilities:
                    add: ["SYS_CHROOT"]