nameOverride: ""
fullnameOverride: ""

global:
  baseDomain: ""
  repo:
    url: https://github.com/whitleykeith/airflow-kubernetes.git
    branch: master


airflow:
  syncWave: 0
  hostName: airflow
  values: 
    defaultAirflowTag: 2.0.2
    config:
      logging:
        colored_console_log: "True"
        remote_logging: "True"
      elasticsearch:
        write_stdout: "True"
      elasticsearch_configs:
        use_ssl: "False"
        verify_certs: "False"
        ssl_show_warn: "False"
      kubernetes:
        delete_worker_pods: True
      core:
        DAGBAG_IMPORT_TIMEOUT: 300
        killed_task_cleanup_time: 604800
      scheduler:
        scheduler_heartbeat_sec: 10
        processor_poll_interval: 30
    dags:
      gitSync:
        enabled: true
        subPath: dags
        depth: 8
    elasticsearch:
      enabled: True
      connection: 
        host: logging-es-http.openshift-logging.svc.cluster.local
        port: 9200
        user: ""
        pass: ""
    webserver:
      replicas: 3


argo:
  syncWave: 0
  hostName: argo
  values: {}


results:
  syncWave: 1
  dashboard:
    values:
      elasticsearch:
        url: perf-results-es-http.perf-results.svc.cluster.local:9200
        indice: perf_scale_ci
        username: elastic
  elastic:
    values: {}


logging: 
  syncWave: 0
  fluentd:
    mergeJsonLogs: false
    values: {}
  elastic:
    values: {}