dashboards: 
  kube_burner_dashboard: 
    id: _XeYNzD7k
    name: kube-burner-thanos
  cluster_dashboard:
    id: ueS4UNS7k
    name: cluster-dash

ignoreTags:
  - baseline
  - install
  - scale_25
  - scale_50



searchIndices: 
  - perf_scale_ci
  