apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argo.syncWave | quote }}
spec:
  host: {{ .Values.argo.hostName }}.{{ .Values.global.baseDomain }}
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect 
    termination: passthrough
  to:
    kind: Service
    name: argocd-server
    weight: 100
  wildcardPolicy: None

