apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.logging.syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  source:
    repoURL: {{ .Values.global.repo.url }}
    path: charts/cluster-logging
    targetRevision: {{ .Values.global.repo.branch }}
    helm:
      releaseName: cluster-logging
{{- with .Values.logging.fluentd.values }}
      values: |-
{{- toYaml . | nindent 8 }}
{{- end }}        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true