apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $_remote_user-$_branch_display_name-airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    mode: playground
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: $_airflow_namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: "1.4.0"
    helm:
      releaseName: airflow
      values: |-
        defaultAirflowRepository: quay.io/cloud-bulldozer/airflow
        defaultAirflowTag: 2.2.3
        airflowVersion: 2.2.3
        executor: KubernetesExecutor
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        images:
          airflow:
            pullPolicy: Always
        postgresql:
          persistence:
            enabled: false
        pgbouncer:
          enabled: true
        config:
          logging:
            colored_console_log: "False"
            remote_logging: "True"
            remote_base_log_folder: s3://perfscale-airflow-logs/$_remote_user
            remote_log_conn_id: S3Logs
          kubernetes:
            delete_worker_pods: True
          core:
            dagbag_import_timeout: 300
            killed_task_cleanup_time: 604800
            dag_file_processor_timeout: 300
            dagbag_import_error_traceback_depth: 4
          scheduler:
            scheduler_heartbeat_sec: 10
            processor_poll_interval: 30
          webserver:
            base_url: http://$_airflow_namespace.$_cluster_domain
            instance_name: $_remote_user
            expose_config: True
            default_ui_timezone: America/New_York
          secrets:
            backend: airflow.providers.hashicorp.secrets.vault.VaultBackend
            backend_kwargs: '{"connections_path": "connections", "variables_path": "variables", "kubernetes_role": "airflow", "auth_type": "kubernetes", "mount_point": "airflow", "url": "http://vault-active.vault.svc.cluster.local:8200"}'
        dags:
          gitSync:
            enabled: true
            subPath: dags
            depth: 8
        webserver:
          replicas: 1
          defaultUser:
            password: $password
        env:
        - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH
          value: repo/
        - name: AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME
          value: "604800"
        - name: GIT_REPO
          value: $_remote_origin_url
        - name: GIT_BRANCH
          value: $_branch      
      parameters:
      - name: dags.gitSync.repo
        value: $_remote_origin_url
      - name: dags.gitSync.branch
        value: $_branch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: airflow
  namespace: $_airflow_namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  host: $_airflow_namespace.$_cluster_domain
  port:
    targetPort: 8080
  to:
    kind: Service
    name: airflow-webserver
    weight: 100
  wildcardPolicy: None
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: $_airflow_namespace
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: $_airflow_namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: airflow-webserver # Name is case sensitive
  namespace: $_airflow_namespace
- kind: ServiceAccount
  name: airflow-worker # Name is case sensitive
  namespace: $_airflow_namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-worker
  namespace: $_airflow_namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "configmaps", "pods"]
  verbs:  ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker
  namespace: $_airflow_namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: $_airflow_namespace
roleRef:
  kind: Role
  name: airflow-worker
  apiGroup: rbac.authorization.k8s.io